Bug/csi 1888 k8s code generation fail
IBM/ibm-block-csi-operator pull request #151
Opened 2021-04-21 06:24 UTC by matancarmeli7

2021-04-21 06:30 UTC, oriyarde commented on cmd/manager/main.go
> +	operatorVersion "github.com/IBM/ibm-block-csi-operator/version"
please merge latest develop into your private branch

2021-04-21 06:39 UTC, oriyarde commented on cmd/manager/main.go
> -	// NOTE: Should enable it back in later version - issue CSI-613
is this diff really necessary?

2021-04-21 06:43 UTC, oriyarde commented on go.mod
> -	github.com/go-openapi/spec v0.17.2
what about go.sum and vendor/?
is there any change to update in the auto-generated code?

2021-04-21 06:47 UTC, oriyarde commented on cmd/manager/main.go
> +	operatorVersion "github.com/IBM/ibm-block-csi-operator/version"
it seems the merge didn't remove this, is this diff really necessary?

2021-04-21 08:06 UTC, zingero requested changes
I agree with Ori

2021-04-29 09:06 UTC, oriyarde approved these changes
LGTM

2021-04-29 10:54 UTC, zingero approved these changes

2021-04-29 11:12 UTC, merged